platform :ios, '7.0'
target 'HuiBaoXian' do
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'SDWebImage', '~> 3.8.2'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'MBProgressHUD', '~> 1.0.0'
end
